### ISSUE TITLE
Conduct cross-browser testing

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/universalviewer#10]
When development gets closer to completion, we should use our cross-browser testing service to ensure all must-have features work on all browsers and make sure we know about any features that don't work on any browser we support.

**Comment by snydman** [comment]
Here are PURL's browser statistics for the past year.  Total new sessions 300,000.

Internet Explorer | 11 | 31,744 | 11%
Safari | 9 | 19,899 | 7%
Chrome | 52.0.2743.116 | 19,844 | 7%
Chrome | 51.0.2704.103 | 12,791 | 4%
Chrome | 52.0.2743.98 | 10,707 | 4%
Chrome | 56.0.2924.87 | 9,920 | 3%
Safari | 10 | 9,757 | 3%
Chrome | 51.0.2704.81 | 8,337 | 3%
Firefox | 47 | 7,797 | 3%
Chrome | 58.0.3029.110 | 7,291 | 2%
Chrome | 55.0.2883.87 | 6,304 | 2%
Firefox | 48 | 5,662 | 2%
Safari | 9.1.2 | 4,822 | 2%
Chrome | 57.0.2987.133 | 4,630 | 2%
Chrome | 49.0.2623.112 | 3,833 | 1%
Chrome | 53.0.2785.143 | 3,577 | 1%
Firefox | 50 | 3,164 | 1%
Firefox | 49 | 2,801 | 1%
Firefox | 53 | 2,188 | 1%
Safari | 8 | 1,761 | 1%
Firefox | 52 | 1,738 | 1%
Firefox | 51 | 1,726 | 1%

**Comment by mejackreed** [comment]
Strange horizontal scrollbar in IE11 Win 7

<img width="761" alt="screen shot 2017-08-01 at 2 49 50 pm" src="https://user-images.githubusercontent.com/1656824/28851400-f688f662-76d6-11e7-9a1e-d949daee726c.png">

In Edge Win10, page reloading to empty iframe
<img width="1040" alt="screen shot 2017-08-01 at 4 36 41 pm" src="https://user-images.githubusercontent.com/1656824/28851482-a347ac18-76d7-11e7-83b1-9acbc7a50754.png">

**Comment by mejackreed** [comment]
I've been able to resolve the IE edge issues. Closing issue as I have tested successfully (and embedded) in major browser versions.
