### ISSUE TITLE
Remove (teardrop) page indicator

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/universalviewer#12]
The page indicator at the bottom of a multi-image object should be removed. Currently, the indicator looks too much like a control and isn’t one, and page numbers don’t update properly. It doesn't seem like a good tradeoff for using up a row of the viewer

----
![universal_viewer_examples 2](https://user-images.githubusercontent.com/101482/28294747-fe9264fa-6b10-11e7-803b-10ab4663c8a6.png)
----

We might reassess if the element could actually work as a slider control, but even then it seems mostly redundant with the scrollbar in the Thumbnails view (though it might provide unique value if you are using the Index view instead).

**Comment by edsilv** [comment]
In config:

```
"searchFooterPanel": {
      "options": {
        "positionMarkerEnabled": false
      }
    },
```

**Comment by mejackreed** [comment]
I think this only displays on items with a IIIF search service. At the moment, I do not believe any of our objects have this behavior.
