### ISSUE TITLE
Keyboard focus is extremely difficult to see in Firefox

### ISSUE THREAD

**Issue by jvine** [sul-dlss/universalviewer#14]
The dotted outline sometimes is truncated by other controls, or overlapping the focused control, or just invisible. 

![screen shot 2017-07-17 at 5 37 43 pm](https://user-images.githubusercontent.com/6945691/28295620-d6399cb6-6b16-11e7-8c1d-83c789c3eb98.png)
![screen shot 2017-07-17 at 5 38 20 pm](https://user-images.githubusercontent.com/6945691/28295615-c858d436-6b16-11e7-94e6-6f83195b2cfc.png)
![screen shot 2017-07-17 at 5 38 12 pm](https://user-images.githubusercontent.com/6945691/28295613-c85419be-6b16-11e7-972f-11ea01bd8851.png)
![screen shot 2017-07-17 at 5 38 04 pm](https://user-images.githubusercontent.com/6945691/28295612-c852f55c-6b16-11e7-9749-67f1f16dd8c0.png)
![screen shot 2017-07-17 at 5 37 55 pm](https://user-images.githubusercontent.com/6945691/28295614-c8566e26-6b16-11e7-994f-fb5bafeab8e2.png)

**Comment by edsilv** [comment]
This is overridable in your theme. e.g.

```
.uv {

   button:focus {
        outline: 1px dotted @btn-focused-border;
    }
}
```
