### ISSUE TITLE
Remove SUL bottom bar in favor of using UV's bottom-based icons

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/universalviewer#17]
Mixing the SUL bottom bar (with the information, download, and sharing icons) with UV creates some UX issues, as well as preventing us from relying completely on the UV UI, which would be more ideal as UV evolves.

Suggest we remove the SUL bar completely and rely on UV's icons for download and sharing. Another benefit is this would enable the zoom icon to be in the same row as the icons, thereby saving a bit of vertical real estate.

**Comment by mejackreed** [comment]
@ggeisler should we style the UV bottom bar like the top?

![screen shot 2017-07-18 at 3 35 34 pm](https://user-images.githubusercontent.com/1656824/28336128-ce24436a-6bce-11e7-9f3f-82d3dcb064c2.png)

**Comment by ggeisler** [comment]
@mejackreed Yeah, that seems like a good approach because it more clearly distinguishes the icons from the main viewing area. But @jvine should weigh in, because I think she mentioned not liking the brown bar with the black UV background. Not sure if she has any other ideas.

**Comment by jvine** [comment]
I don't love the brown with black, but I don't know if I want to introduce another colour, either.

I think we're also proposing that we would use the default "More information" sidebar slider in place of the "i" icon.

**Comment by mejackreed** [comment]
I'm confused. So remove the `i` from the bottom panel in favor of right panel?

Like this?

<img width="660" alt="screen shot 2017-07-18 at 7 10 07 pm" src="https://user-images.githubusercontent.com/1656824/28343717-c02f6456-6bec-11e7-8fb8-cf1588df64ad.png">

One thing to note here is that right side panel disappears at `663px`. I'm not sure how configurable that is but can look into if need be.

**Comment by mejackreed** [comment]
@jvine we could also look at doing something like this to add more consistency:

<img width="1061" alt="screen shot 2017-07-18 at 7 15 56 pm" src="https://user-images.githubusercontent.com/1656824/28343880-95ed4504-6bed-11e7-90ad-0e974f047d2c.png">

I didn't fully style everything (just the main background) but I think this is quite doable for theming/skinning

**Comment by mejackreed** [comment]
@jvine we could also look at doing something like this to add more consistency:

<img width="1061" alt="screen shot 2017-07-18 at 7 15 56 pm" src="https://user-images.githubusercontent.com/1656824/28343880-95ed4504-6bed-11e7-90ad-0e974f047d2c.png">

I didn't fully style everything (just the main background) but I think this is quite doable for theming/skinning

**Comment by jvine** [comment]
> I'm confused. So remove the i from the bottom panel in favor of right panel?

Yes. But:

> One thing to note here is that right side panel disappears at 663px. I'm not sure how configurable that is but can look into if need be.

That's not good. Does it turn into something else? Just goes away? 

> we could also look at doing something like this

I think that looks busy. I don't mind the black background at all; just don't love the brown with it. I don't know what else there is in our palette that would be better. One option would be to use the same very dark grey that they use for the panels (#211f1f) for the header and footer. Technically not in our palette, but...

**Comment by mejackreed** [comment]
> That's not good. Does it turn into something else? Just goes away?

It goes away. I can look into keeping it around, but our mobile view feels even more busy here. (this is me force enabling it to show what it looks like)

![screen shot 2017-07-19 at 7 38 32 am](https://user-images.githubusercontent.com/1656824/28365156-6895d374-6c55-11e7-9184-3283f6b71420.png)

> I think that looks busy. I don't mind the black background at all; just don't love the brown with it. I don't know what else there is in our palette that would be better. One option would be to use the same very dark grey that they use for the panels (#211f1f) for the header and footer. Technically not in our palette, but...

Understood about the business. Then are we looking to change the colors for all the embed viewers or will image viewer just be different?

**Comment by mejackreed** [comment]
Is this issue resolved now? I think we can close, reopen if needed.
