### ISSUE TITLE
Replace "X" on modals with Close button

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/universalviewer#20]
The close icon on the UV modals doesn't feel quite right; it gives the viewer a bit of an unsophisticated feel:

![universal_viewer_examples 4](https://user-images.githubusercontent.com/101482/28330323-0169718c-6ba2-11e7-88a4-08a02406fca7.png)
----
We recommend replacing the current close icon with a close button in the modal itself:

![universal_viewer_examples 5](https://user-images.githubusercontent.com/101482/28330410-5534ecec-6ba2-11e7-88c9-d2aa99527153.png)
----
![universal_viewer_examples 3](https://user-images.githubusercontent.com/101482/28330458-879f664e-6ba2-11e7-9845-9e4aaec100ce.png)
---
Styling the close button with the Bootstrap styling for `btn-default` should work fine.

Minor related point: I'd give all the modal buttons a border-radius of 4px or so, just because there are already a lot of sharp corners used in the modal.

**Comment by mejackreed** [comment]
We think the approach here is to modify `Dialogue.ts` locally to change how the markup is rendered (and then of course modify styling?). `$closeButton` seems to be the relevant thing.

**Comment by mejackreed** [comment]
@aeschylus and I have paired looking into this, and it appears more complex than originally thought. The intent here is to not only add the "Close" text but also change the location of this button. This html syntax would need to be overridden differently in each UV class that uses this. Most of these are `*Dialougue` classes and the change likely wouldn't be global.

A few ways ahead here:
 - make local modifications and now support a local fork ( we don't like this option )
 - Make the location of the close box configurable
 - Move the location of the close box entirely 

What is the most viable way?

**Comment by aeschylus** [comment]
Part of what complicates this is the inability to access the UV's own model of the interface at runtime, or to supply an override class through an externally-maintained set of "plugins", or override objects. The typescript toolchain closes us out of the object hierarchy.

However, if there is a way to do an override (we'd have to hear from @edsilv on that I think), that is a 4th option.

**Comment by aeschylus** [comment]
The base Dialogue has had a buttons container added and a config option has been added to place the close button in this container. We will need to confirm that the styling and events are working in the following inheriting classes (for personal reference/as a checklist):

- [ ] Settings Dialogue
- [ ] Download Dialogue
- [ ] Auth Dialogue
- [ ] Clickthrough Dialogue
- [ ] Help Dialogue
- [ ] External Content Dialogue
- [ ] Login Dialogue
- [ ] Share Dialogue
- [ ] More Info Dialogue
- [ ] Restricted Dialogue

**Comment by aeschylus** [comment]
@edsilv has said we can submit this as a PR to v3 with the config option, then it can be selected in our theme.
