### ISSUE TITLE
Simplify login/authentication process

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/universalviewer#24]
The colored information banner at the top of the viewer for logging in is a good first step for authentication, but do we need the subsequent modal windows that appear when the user 1) clicks login, and 2) clicks log in and then Cancel?

Could the login button go straight to the institution auth challenge?

That would eliminate the modal that has the Cancel button, so the subsequent modal would also be eliminated. If the user fails the auth challenge, they could just be returned to the initial state and the user can either try the log in button again or, realizing they don't have the necessary credentials, click the close "X" to remove the information banner.

Also, perhaps we want to update the text in the banner to be a bit more generic, since logging in could affect different aspects of the experience, depending on what the access rights are:

> Log in to view with all available features.

Finally, a minor issue but when we implement for Stanford, we'll probably want to change the background color of the information banner to something in the Stanford color palette (and maybe some with less contrast, so the lazy, unauthenticated user can use the viewer without closing the banner and not be too distracted by it).

**Comment by snydman** [comment]
Ultimately I think we may want  to break this into multiple tickets. Some of this is more critical than others.

**Comment by ggeisler** [comment]
I'm closing this to simply things, since everything proposed here is now in tickets #31, #32, and #33.
