### ISSUE TITLE
Fix styling at mobile view

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/universalviewer#27]
There are issues with right panel disappears as well as modals popping into wrong places.

**Comment by snydman** [comment]
need to break this ticket up

**Comment by mejackreed** [comment]
# bb000kq3835

![screen shot 2017-07-19 at 4 39 53 pm](https://user-images.githubusercontent.com/1656824/28388497-ee6a96a6-6ca0-11e7-93f6-2868d3d2aac1.png)

**Comment by edsilv** [comment]
have reduced the width of auth dialogues to 250px on mobile, fork sync needed.

**Comment by aeschylus** [comment]
@edsilv There seems to be a problem with the yellow bar disappearing in the mobile tester page with non-"standard" auth (Kitty Joyner object). The standard auth looks much better though.

**Comment by mejackreed** [comment]
Most of this has been resolved with https://github.com/UniversalViewer/universalviewer/commit/f2ceb32719d96b6c25a52a48130bbc20debc3cf5 Closing this issue in favor of more specific problems that crop up.
