### ISSUE TITLE
Add ARIA support for show/hide and modal interactions

### ISSUE THREAD

**Issue by jvine** [sul-dlss/universalviewer#28]
Add aria-expanded state to show/hide and modal interactions.

**Comment by mejackreed** [comment]
- [ ] rightPanel
 - [ ] leftPanel
 - [ ] informationBox
 - [ ] ....

**Comment by mejackreed** [comment]
Resolved upstream in UV https://github.com/UniversalViewer/universalviewer/pull/485 . Deployed to UAT
