### ISSUE TITLE
Update text in Login banner

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/universalviewer#32]
(Broken out from #24)

Update the text in the banner to be a bit more generic, since logging in could affect different aspects of the experience, depending on what the access rights are. One possibility:

> Log in to view with all available features.

**Comment by mejackreed** [comment]
This string is coming directly from the config in uv .

**Comment by edsilv** [comment]
This now comes from the info.json's login service `label` and `confirmLabel` properties. (For sync needed)

**Comment by ggeisler** [comment]
@jvine Do you have opinions on updating the banner text? Since there are a number of possibilities of what the user gets by logging in (depending on the combination of zoom and download rights that apply to the object), I suggested above something fairly generic that implies there are benefits from logging in without getting into specifics:

> Log in to view with all available features.

**Comment by jvine** [comment]
@ggeisler Agree that if we can't predict (can we?) what will be available after login, we should be generic. Maybe even:
> Log in to access all available features.

?

**Comment by ggeisler** [comment]
@jvine Sure, I like that modification better.
