### ISSUE TITLE
Mini-map navigator renders inconsistently for multi page objects

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/universalviewer#49]
The mini-map navigator has some rendering quirks after updating the to the latest UV master branch (a couple weeks ago).  When I say "mini-map navigator" what I mean is the UI element highlighted in the red box in the screenshot below.

<img width="1167" alt="mini-map-navigator" src="https://user-images.githubusercontent.com/96776/35412111-fe34b6ba-01cf-11e8-9424-8b606061dd24.png">

## Steps to reproduce (in UAT)
1. Go to a record that renders a viewer (cc842mn9348)
    * Note that the mini-map navigator **does** show up on the first page 
1. Navigate to the 2nd page (using the arrow button navigation in the viewer or clicking on an item in the Contents side panel).
    * Note that the mini-map navigator **does not** show up on the 2nd, or any subsequent page

## Current Behavior (in UAT)
The mini-map navigation does not show up on any subsequent page.

## Expected Behavior (which you can see in production)
The mini-map navigation continues to render through paging to different documents.

## Other Information
You can get the mini-map navigation to show up be re-sizing the page.  This makes me thing that this may have something to do w/ the changes that were made to the responsive features of UV.  It renders correctly on initialization, and on resize, but it looks like whatever is checking on page navigation to see if the mini-map should render is either getting the wrong state or not executing at all.

**Comment by mejackreed** [comment]
I think that this is the commit that removed the navigator based on sizing of the window: https://github.com/UniversalViewer/universalviewer/commit/28b5b21402a04f9f242594b3eab326a9faa4dbb9

**Comment by mejackreed** [comment]
@ggeisler is their a certain range of width/heights that we want the navigator to appear on? We can likely make this modification using an updated config.

**Comment by jkeck** [comment]
@mejackreed we have updated our variables to disable all other screen widths and should be getting this feature in all modalities.  sul-dlss/uv-en-GB-theme#1

You'll notice in the example above that the rendering of the navigator can be inconsistent based on which canvas you're loading (when it is expected to be showing at all times).
