### ISSUE TITLE
Remove pagination controls in title bar

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/universalviewer#5]
![bugatti_type_51a__road__amp__track_salon_january_1957___stanford_digital_repository](https://user-images.githubusercontent.com/101482/28293566-9a785918-6b09-11e7-8e87-9983fd2f10b2.png)
----
These pagination controls in the viewer title bar are arguably unnecessary, given the user can 1) navigate forward and backward by page using the next and previous controls in the main viewer area, and 2) navigate in larger jumps pretty quickly using the Contents scroll bar. The most useful thing we'd lose by removing the controls is the jump-to-page control, but that seems worth it given the UX issues the pagination controls introduce.

**Comment by jvine** [comment]
Note that there are also accessibility issues with the controls as they stand - WAVE is reporting missing or empty field labels; and button controls are expressed as links without text.
