### ISSUE TITLE
More Information Side Panel Investigation

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/universalviewer#50]
Currently, in production, the More Information side panel is hidden in smaller viewer sizes (e.g. in Exhibits the More Information panel is not visible while the More information panel is visible in PURL, which is fullscreen).  This is due to the responsive feature of UV.

Since we've updated UV has changed its UV's responsive behavior.  We're now effectively disabling the additional screen sizes provided by UV's responsive behavior, except for the largest screen size.  This causes all the UI elements to render in our case.

AFAICT so far, the only additional UI component that we're now rendering in our updated version is the More Information sidebar.  The mini-map navigator is also responsive dependent, but up on all screen sizes in production currently.

Questions:
- Is it desirable for us to hide the More Information sidebar in smaller viewer sizes? (the current production behavior)
- If so, is there anyway to accomplish that with the current UV responsive behavior while also retaining the mini-map navigator?

**Comment by LlGC-szw** [comment]
For us the main problem with hiding both the side panels is, when you have items in a tree structure you can only navigate within the current item you are viewing. So, for example if you are viewing a journal title, you can only view the pages for the edition open and you cannot change to the next date available. 
We have discussed moving those panels to the bottom (?) of the xs view screen so at least they are there for the user when they need them.

**Comment by mejackreed** [comment]
@jkeck I think this is resolved now with 1182b1bee3386989b892ab888a5d16bdcd873653 . Can you confirm?

**Comment by jkeck** [comment]
👍 We can open a separate issue if we decide to change the behavior from what we currently have in UAT.
