### ISSUE TITLE
More information panel label does not appear in UV in prod

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/universalviewer#52]
**UV version:**

```
 universalviewer@2.0.1
```

**I'm submitting a:**

- [X] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

In `universalviewer@2.0.1`, the More Information panel label does not appear at small screen sizes: 

![screen shot 2018-01-31 at 1 20 47 pm](https://user-images.githubusercontent.com/73732/35648145-92f3b8ce-0689-11e8-960e-f383e9e3bf3f.png)

The change to responsiveness in version 3 leads to the panel label to appear:

![screen shot 2018-01-31 at 1 22 52 pm](https://user-images.githubusercontent.com/73732/35648216-df0a98cc-0689-11e8-988f-b62025488d7a.png)

**Expected behavior:**

The "More Information" label should appear at small screen sizes.

**Comment by mejackreed** [comment]
@jkeck effectively fixed this in sul-embed with https://github.com/sul-dlss/sul-embed/pull/846 with some of the metrics configured. We need to just confirm that we  want everything to show up on all screen sizes.
