### ISSUE TITLE
"Previous result" link for search results does not work

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/universalviewer#53]
**UV version:**

```
 universalviewer@3.0.0 in sul-purl-uat
```

**I'm submitting a:**

- bug report

**Current behavior:**

When navigating through search results, the "previous result" link does not respond; the "next result" works as expected as however.

**Expected behavior:**

Based on the changes related to #46, I'm expecting that the previous result link should take me to the previous page that contains matches for the search. 

**Steps to reproduce:**

* Load UV for a purl in sul-purl-uat (e.g. <https://sul-purl-uat.stanford.edu/zb477wc3656>)
* Type in a search term (e.g. `indictment`) and submit
* Click the "Next Result" one or more times
* Clicking previous result does not respond

![out](https://user-images.githubusercontent.com/73732/36080708-3a266002-0f49-11e8-8364-eab468ae1c16.gif)

**Comment by jkeck** [comment]
We've tracked this down to adding the `zoomToSearchResultEnabled: false` config option.  It appears that UV attached the events to the previous button when zooming into the result. We're investigating possible solutions, but will most likely end up submitting a ticket to UV about this.
