### ISSUE TITLE
Change icon controls to buttons from links

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/universalviewer#6]
It looks like the settings, view options, and pagination (if we don't remove them via #5) controls in the viewer are coded as HTML links. These should be coded as buttons instead. 

![strad___and_other_stories___stanford_digital_repository](https://user-images.githubusercontent.com/101482/28293831-0cb7adb6-6b0b-11e7-8632-e9f21cb749fd.png)

**Comment by mejackreed** [comment]
Tracking upstream here: https://github.com/UniversalViewer/universalviewer/issues/479

**Comment by mejackreed** [comment]
Resolved upstream in UV here: https://github.com/UniversalViewer/universalviewer/pull/491
