### ISSUE TITLE
Analysis: current 3D format support

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/universalviewer#67]
What 3D formats does UV support?
What version of UV are we using? What version of virtex is it using?
Does a newer version provide additional support?

Let's answer these questions before heading into a cross-team meeting re: 3D.

**Comment by cbeer** [comment]
Virtex claims to support CORTO, DRACO, Obj, PLY, ThreeJS, GLTF (although there are more recent improvements upstream..)

We're using virtex https://github.com/sul-dlss/universalviewer/blob/876fd5f510db4e9ac47ef658a7883c5e7b6f691c/package.json#L91
