### ISSUE TITLE
Suppress jump-to-page typeahead

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/universalviewer#7]
If we don't remove the pagination controls via #5, or if we decide to just keep the jump-to-page control (the most useful part of the pagination controls), we should **not** display the typeahead for the page input. It's distracting and doesn't really provide value in this context.

![strad___and_other_stories___stanford_digital_repository](https://user-images.githubusercontent.com/101482/28293908-928de982-6b0b-11e7-96b7-3d2ee24522bc.png)

**Comment by mejackreed** [comment]
Closed since we disabled pagination.
